ribbon:
  ReadTimeout: 55000
  ConnectTimeout: 55000
feign:
  client:
    config:
      feignName:
        connectTimeout: 15000
        readTimeout: 15000
security:
  basic:
    enabled: false


spring:
  redis:
    database: 2
    host: 120.76.176.30
    password: lpladUS6
    timeout: 150ms
    port: 16379
    jedis:
      pool:
        max-active: 80
        max-idle: 8
        max-wait: -1ms
        min-idle: 1