package com.autumn.wallet.domain.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;

public class Tmicroaddressinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.maiid
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "主键")
    @TableId(type = IdType.AUTO)
    private Integer maiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.accountid
     *
     * @mbg.generated
     */
    private Integer accountid;
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.coinid
     *
     * @mbg.generated
     */
    private Integer coinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.maddress
     *
     * @mbg.generated
     */
    private String maddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.mtotalaccquantity
     *
     * @mbg.generated
     */
    private BigDecimal mtotalaccquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.msymbol
     *
     * @mbg.generated
     */
    private String msymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.mencprikey
     *
     * @mbg.generated
     */
    private String mencprikey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.mcreatepath4
     *
     * @mbg.generated
     */
    private Integer mcreatepath4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.mcreatepath5
     *
     * @mbg.generated
     */
    private Integer mcreatepath5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicroaddressinfo.mregid
     *
     * @mbg.generated
     */
    private String mregid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.maiid
     *
     * @return the value of tmicroaddressinfo.maiid
     *
     * @mbg.generated
     */
    public Integer getMaiid() {
        return maiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.maiid
     *
     * @param maiid the value for tmicroaddressinfo.maiid
     *
     * @mbg.generated
     */
    public void setMaiid(Integer maiid) {
        this.maiid = maiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.accountid
     *
     * @return the value of tmicroaddressinfo.accountid
     *
     * @mbg.generated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.accountid
     *
     * @param accountid the value for tmicroaddressinfo.accountid
     *
     * @mbg.generated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.coinid
     *
     * @return the value of tmicroaddressinfo.coinid
     *
     * @mbg.generated
     */
    public Integer getCoinid() {
        return coinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.coinid
     *
     * @param coinid the value for tmicroaddressinfo.coinid
     *
     * @mbg.generated
     */
    public void setCoinid(Integer coinid) {
        this.coinid = coinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.maddress
     *
     * @return the value of tmicroaddressinfo.maddress
     *
     * @mbg.generated
     */
    public String getMaddress() {
        return maddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.maddress
     *
     * @param maddress the value for tmicroaddressinfo.maddress
     *
     * @mbg.generated
     */
    public void setMaddress(String maddress) {
        this.maddress = maddress == null ? null : maddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.mtotalaccquantity
     *
     * @return the value of tmicroaddressinfo.mtotalaccquantity
     *
     * @mbg.generated
     */
    public BigDecimal getMtotalaccquantity() {
        return mtotalaccquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.mtotalaccquantity
     *
     * @param mtotalaccquantity the value for tmicroaddressinfo.mtotalaccquantity
     *
     * @mbg.generated
     */
    public void setMtotalaccquantity(BigDecimal mtotalaccquantity) {
        this.mtotalaccquantity = mtotalaccquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.msymbol
     *
     * @return the value of tmicroaddressinfo.msymbol
     *
     * @mbg.generated
     */
    public String getMsymbol() {
        return msymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.msymbol
     *
     * @param msymbol the value for tmicroaddressinfo.msymbol
     *
     * @mbg.generated
     */
    public void setMsymbol(String msymbol) {
        this.msymbol = msymbol == null ? null : msymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.mencprikey
     *
     * @return the value of tmicroaddressinfo.mencprikey
     *
     * @mbg.generated
     */
    public String getMencprikey() {
        return mencprikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.mencprikey
     *
     * @param mencprikey the value for tmicroaddressinfo.mencprikey
     *
     * @mbg.generated
     */
    public void setMencprikey(String mencprikey) {
        this.mencprikey = mencprikey == null ? null : mencprikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.mcreatepath4
     *
     * @return the value of tmicroaddressinfo.mcreatepath4
     *
     * @mbg.generated
     */
    public Integer getMcreatepath4() {
        return mcreatepath4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.mcreatepath4
     *
     * @param mcreatepath4 the value for tmicroaddressinfo.mcreatepath4
     *
     * @mbg.generated
     */
    public void setMcreatepath4(Integer mcreatepath4) {
        this.mcreatepath4 = mcreatepath4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.mcreatepath5
     *
     * @return the value of tmicroaddressinfo.mcreatepath5
     *
     * @mbg.generated
     */
    public Integer getMcreatepath5() {
        return mcreatepath5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.mcreatepath5
     *
     * @param mcreatepath5 the value for tmicroaddressinfo.mcreatepath5
     *
     * @mbg.generated
     */
    public void setMcreatepath5(Integer mcreatepath5) {
        this.mcreatepath5 = mcreatepath5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicroaddressinfo.mregid
     *
     * @return the value of tmicroaddressinfo.mregid
     *
     * @mbg.generated
     */
    public String getMregid() {
        return mregid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicroaddressinfo.mregid
     *
     * @param mregid the value for tmicroaddressinfo.mregid
     *
     * @mbg.generated
     */
    public void setMregid(String mregid) {
        this.mregid = mregid == null ? null : mregid.trim();
    }
}