package com.autumn.domain.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

public class Tmicrorechargelog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mrlid
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "主键")
    @TableId(type = IdType.AUTO)
    private Integer mrlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.accountid
     *
     * @mbg.generated
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.maddress
     *
     * @mbg.generated
     */
    private String maddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mtxid
     *
     * @mbg.generated
     */
    private String mtxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mquantity
     *
     * @mbg.generated
     */
    private BigDecimal mquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mblockhash
     *
     * @mbg.generated
     */
    private String mblockhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mblockheight
     *
     * @mbg.generated
     */
    private Integer mblockheight;
    private Integer mcoinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mtxisvaild
     *
     * @mbg.generated
     */
    private Boolean mtxisvaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.msymbol
     *
     * @mbg.generated
     */
    private String msymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mpsymbol
     *
     * @mbg.generated
     */
    private String mpsymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mtxistoken
     *
     * @mbg.generated
     */
    private Boolean mtxistoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmicrorechargelog.mrecivetime
     *
     * @mbg.generated
     */
    private Date mrecivetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mrlid
     *
     * @return the value of tmicrorechargelog.mrlid
     *
     * @mbg.generated
     */
    public Integer getMrlid() {
        return mrlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mrlid
     *
     * @param mrlid the value for tmicrorechargelog.mrlid
     *
     * @mbg.generated
     */
    public void setMrlid(Integer mrlid) {
        this.mrlid = mrlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.accountid
     *
     * @return the value of tmicrorechargelog.accountid
     *
     * @mbg.generated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.accountid
     *
     * @param accountid the value for tmicrorechargelog.accountid
     *
     * @mbg.generated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.userid
     *
     * @return the value of tmicrorechargelog.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.userid
     *
     * @param userid the value for tmicrorechargelog.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.maddress
     *
     * @return the value of tmicrorechargelog.maddress
     *
     * @mbg.generated
     */
    public String getMaddress() {
        return maddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.maddress
     *
     * @param maddress the value for tmicrorechargelog.maddress
     *
     * @mbg.generated
     */
    public void setMaddress(String maddress) {
        this.maddress = maddress == null ? null : maddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mtxid
     *
     * @return the value of tmicrorechargelog.mtxid
     *
     * @mbg.generated
     */
    public String getMtxid() {
        return mtxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mtxid
     *
     * @param mtxid the value for tmicrorechargelog.mtxid
     *
     * @mbg.generated
     */
    public void setMtxid(String mtxid) {
        this.mtxid = mtxid == null ? null : mtxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mquantity
     *
     * @return the value of tmicrorechargelog.mquantity
     *
     * @mbg.generated
     */
    public BigDecimal getMquantity() {
        return mquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mquantity
     *
     * @param mquantity the value for tmicrorechargelog.mquantity
     *
     * @mbg.generated
     */
    public void setMquantity(BigDecimal mquantity) {
        this.mquantity = mquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mblockhash
     *
     * @return the value of tmicrorechargelog.mblockhash
     *
     * @mbg.generated
     */
    public String getMblockhash() {
        return mblockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mblockhash
     *
     * @param mblockhash the value for tmicrorechargelog.mblockhash
     *
     * @mbg.generated
     */
    public void setMblockhash(String mblockhash) {
        this.mblockhash = mblockhash == null ? null : mblockhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mblockheight
     *
     * @return the value of tmicrorechargelog.mblockheight
     *
     * @mbg.generated
     */
    public Integer getMblockheight() {
        return mblockheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mblockheight
     *
     * @param mblockheight the value for tmicrorechargelog.mblockheight
     *
     * @mbg.generated
     */
    public void setMblockheight(Integer mblockheight) {
        this.mblockheight = mblockheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mtxisvaild
     *
     * @return the value of tmicrorechargelog.mtxisvaild
     *
     * @mbg.generated
     */
    public Boolean getMtxisvaild() {
        return mtxisvaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mtxisvaild
     *
     * @param mtxisvaild the value for tmicrorechargelog.mtxisvaild
     *
     * @mbg.generated
     */
    public void setMtxisvaild(Boolean mtxisvaild) {
        this.mtxisvaild = mtxisvaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.msymbol
     *
     * @return the value of tmicrorechargelog.msymbol
     *
     * @mbg.generated
     */
    public String getMsymbol() {
        return msymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.msymbol
     *
     * @param msymbol the value for tmicrorechargelog.msymbol
     *
     * @mbg.generated
     */
    public void setMsymbol(String msymbol) {
        this.msymbol = msymbol == null ? null : msymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mpsymbol
     *
     * @return the value of tmicrorechargelog.mpsymbol
     *
     * @mbg.generated
     */
    public String getMpsymbol() {
        return mpsymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mpsymbol
     *
     * @param mpsymbol the value for tmicrorechargelog.mpsymbol
     *
     * @mbg.generated
     */
    public void setMpsymbol(String mpsymbol) {
        this.mpsymbol = mpsymbol == null ? null : mpsymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mtxistoken
     *
     * @return the value of tmicrorechargelog.mtxistoken
     *
     * @mbg.generated
     */
    public Boolean getMtxistoken() {
        return mtxistoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mtxistoken
     *
     * @param mtxistoken the value for tmicrorechargelog.mtxistoken
     *
     * @mbg.generated
     */
    public void setMtxistoken(Boolean mtxistoken) {
        this.mtxistoken = mtxistoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmicrorechargelog.mrecivetime
     *
     * @return the value of tmicrorechargelog.mrecivetime
     *
     * @mbg.generated
     */
    public Date getMrecivetime() {
        return mrecivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmicrorechargelog.mrecivetime
     *
     * @param mrecivetime the value for tmicrorechargelog.mrecivetime
     *
     * @mbg.generated
     */
    public void setMrecivetime(Date mrecivetime) {
        this.mrecivetime = mrecivetime;
    }

    public Integer getMcoinid() {
        return mcoinid;
    }

    public void setMcoinid(Integer mcoinid) {
        this.mcoinid = mcoinid;
    }
}